import 'dart:ui' as ui show WindowPadding;
import 'package:intl/intl.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
import 'package:lottie/lottie.dart';
import 'package:project_structure/locator.dart';
import 'package:project_structure/service/storage/storage_service.dart';
import 'package:project_structure/util/theme/theme_constant.dart';
import 'package:shimmer/shimmer.dart';
import 'package:flutter_svg/flutter_svg.dart';

part 'double_extension.dart';
part 'align_extension.dart';
part 'padding_extension.dart';
part 'text_style_extension.dart';
part 'string_extension.dart';
part 'svg_extension.dart';
part 'shimmer_extension.dart';
